nelmio_api_doc:
    models: { use_jms: false }
    documentation:
        servers:
          - url: https://127.0.0.1:8000/api/doc
            description: API over HTTP
        info:
            title: BileMo 
            description: Téléphones mobiles haut de gamme.
            version: 1.0.0
            
        tags:
            - name: "Customer"
              description: "Customer related endpoints"
            - name: "Phones"
              description: "Phones related endpoints"
            - name: "Client"
              description: "Client related endpoints"
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
    areas:
        default:
            disable_default_routes: true


        
